### ISSUE TITLE
No gulpfile found

### ISSUE THREAD

**Issue by grusingh** [Philo/cake-gulp#12]
When setting WorkingDirectory and running build.ps1 get error: No gulpfile found

Without setting WorkingDirectory, gulpfile is found, but then node_modules are not found (looks in parent directory for node_modules)
module.js:471
    throw err;
    ^

Error: Cannot find module 'C:\xxx\node_modules\gulp\bin\gulp.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

**Comment by Philo** [comment]
Hi @gursharn,

Could you please post a snippet of your cake build that is running npm and also the diagnostic output from the build.

Thanks

**Comment by grusingh** [comment]
Task("Gulp")
    .Does(() =>
{
    var setting = new NpmInstallSettings{
        LogLevel = NpmLogLevel.Info,
        WorkingDirectory = "./ui_folder/",
        Production = true
    };

    NpmInstall(setting);

    Gulp.Local.Execute(settings => {
        settings.WithGulpFile("./ui_folder/gulpfile.js");
        settings.WithArguments("debug --env=prod");
        settings.WorkingDirectory = "./ui_folder/";
    });
});

Task("Default")
    .IsDependentOn("Gulp");

RunTarget(target);

**Comment by Philo** [comment]
Do you have gulp installed locally? Via the package.json?

Could also try explicitly installing gulp:

NPMInstall("gulp")

**Comment by pascalberger** [comment]
Closing due to inactivity
